language: go

go:
- tip
script:
- wget https://github.com/SeaHOH/GotoX/archive/master.zip
- unzip master.zip 
- wget https://github.com/SeaHOH/GotoX/archive/win_py_portable.zip
- unzip win_py_portable.zip 

- cp -R GotoX-master GotoX-win32
- cp -R GotoX-master GotoX-win64

- cp -R GotoX-win_py_portable/cp35-win32/python/* GotoX-win32/python
- cp -R GotoX-win_py_portable/cp35-win_amd64/python/* GotoX-win64/python

- zip -r GotoX-${TRAVIS_TAG}-win32.zip GotoX-win32
- zip -r GotoX-${TRAVIS_TAG}-win64.zip GotoX-win64

- sha1sum *.zip


deploy:
  provider: releases
  api_key:
    secure: ${TOKEN}
  file: 
    - GotoX-${TRAVIS_TAG}-win32.zip
    - GotoX-${TRAVIS_TAG}-win64.zip
  skip_cleanup: true
  on:
    tags: true
    repo: Kisesy/test
